/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "logic_constants.h"

namespace ss { namespace logic {

const logicConstants g_logic_constants;

logicConstants::logicConstants() {
}

}} // namespace

