/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LogicService_H
#define LogicService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "logic_types.h"

namespace ss { namespace logic {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class LogicServiceIf {
 public:
  virtual ~LogicServiceIf() {}
  virtual void do_logic(Rsp& _return, const Req& req) = 0;
};

class LogicServiceIfFactory {
 public:
  typedef LogicServiceIf Handler;

  virtual ~LogicServiceIfFactory() {}

  virtual LogicServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(LogicServiceIf* /* handler */) = 0;
};

class LogicServiceIfSingletonFactory : virtual public LogicServiceIfFactory {
 public:
  LogicServiceIfSingletonFactory(const boost::shared_ptr<LogicServiceIf>& iface) : iface_(iface) {}
  virtual ~LogicServiceIfSingletonFactory() {}

  virtual LogicServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(LogicServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<LogicServiceIf> iface_;
};

class LogicServiceNull : virtual public LogicServiceIf {
 public:
  virtual ~LogicServiceNull() {}
  void do_logic(Rsp& /* _return */, const Req& /* req */) {
    return;
  }
};

typedef struct _LogicService_do_logic_args__isset {
  _LogicService_do_logic_args__isset() : req(false) {}
  bool req :1;
} _LogicService_do_logic_args__isset;

class LogicService_do_logic_args {
 public:

  LogicService_do_logic_args(const LogicService_do_logic_args&);
  LogicService_do_logic_args& operator=(const LogicService_do_logic_args&);
  LogicService_do_logic_args() {
  }

  virtual ~LogicService_do_logic_args() throw();
  Req req;

  _LogicService_do_logic_args__isset __isset;

  void __set_req(const Req& val);

  bool operator == (const LogicService_do_logic_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const LogicService_do_logic_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogicService_do_logic_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LogicService_do_logic_pargs {
 public:


  virtual ~LogicService_do_logic_pargs() throw();
  const Req* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _LogicService_do_logic_result__isset {
  _LogicService_do_logic_result__isset() : success(false) {}
  bool success :1;
} _LogicService_do_logic_result__isset;

class LogicService_do_logic_result {
 public:

  LogicService_do_logic_result(const LogicService_do_logic_result&);
  LogicService_do_logic_result& operator=(const LogicService_do_logic_result&);
  LogicService_do_logic_result() {
  }

  virtual ~LogicService_do_logic_result() throw();
  Rsp success;

  _LogicService_do_logic_result__isset __isset;

  void __set_success(const Rsp& val);

  bool operator == (const LogicService_do_logic_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const LogicService_do_logic_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogicService_do_logic_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _LogicService_do_logic_presult__isset {
  _LogicService_do_logic_presult__isset() : success(false) {}
  bool success :1;
} _LogicService_do_logic_presult__isset;

class LogicService_do_logic_presult {
 public:


  virtual ~LogicService_do_logic_presult() throw();
  Rsp* success;

  _LogicService_do_logic_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class LogicServiceClient : virtual public LogicServiceIf {
 public:
  LogicServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  LogicServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void do_logic(Rsp& _return, const Req& req);
  void send_do_logic(const Req& req);
  void recv_do_logic(Rsp& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class LogicServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<LogicServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (LogicServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_do_logic(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  LogicServiceProcessor(boost::shared_ptr<LogicServiceIf> iface) :
    iface_(iface) {
    processMap_["do_logic"] = &LogicServiceProcessor::process_do_logic;
  }

  virtual ~LogicServiceProcessor() {}
};

class LogicServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  LogicServiceProcessorFactory(const ::boost::shared_ptr< LogicServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< LogicServiceIfFactory > handlerFactory_;
};

class LogicServiceMultiface : virtual public LogicServiceIf {
 public:
  LogicServiceMultiface(std::vector<boost::shared_ptr<LogicServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~LogicServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<LogicServiceIf> > ifaces_;
  LogicServiceMultiface() {}
  void add(boost::shared_ptr<LogicServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void do_logic(Rsp& _return, const Req& req) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->do_logic(_return, req);
    }
    ifaces_[i]->do_logic(_return, req);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class LogicServiceConcurrentClient : virtual public LogicServiceIf {
 public:
  LogicServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  LogicServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void do_logic(Rsp& _return, const Req& req);
  int32_t send_do_logic(const Req& req);
  void recv_do_logic(Rsp& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

}} // namespace

#endif
