/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef logic_TYPES_H
#define logic_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace ss { namespace logic {

class Req;

class Rsp;

typedef struct _Req__isset {
  _Req__isset() : msg(true) {}
  bool msg :1;
} _Req__isset;

class Req {
 public:

  Req(const Req&);
  Req& operator=(const Req&);
  Req() : msg("") {
  }

  virtual ~Req() throw();
  std::string msg;

  _Req__isset __isset;

  void __set_msg(const std::string& val);

  bool operator == (const Req & rhs) const
  {
    if (__isset.msg != rhs.__isset.msg)
      return false;
    else if (__isset.msg && !(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const Req &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Req & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Req &a, Req &b);

inline std::ostream& operator<<(std::ostream& out, const Req& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _Rsp__isset {
  _Rsp__isset() : status(true) {}
  bool status :1;
} _Rsp__isset;

class Rsp {
 public:

  Rsp(const Rsp&);
  Rsp& operator=(const Rsp&);
  Rsp() : status("unknown") {
  }

  virtual ~Rsp() throw();
  std::string status;

  _Rsp__isset __isset;

  void __set_status(const std::string& val);

  bool operator == (const Rsp & rhs) const
  {
    if (__isset.status != rhs.__isset.status)
      return false;
    else if (__isset.status && !(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const Rsp &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Rsp & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Rsp &a, Rsp &b);

inline std::ostream& operator<<(std::ostream& out, const Rsp& obj)
{
  obj.printTo(out);
  return out;
}

}} // namespace

#endif
