/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef logic_CONSTANTS_H
#define logic_CONSTANTS_H

#include "logic_types.h"

namespace ss { namespace logic {

class logicConstants {
 public:
  logicConstants();

};

extern const logicConstants g_logic_constants;

}} // namespace

#endif
